theme: jekyll-theme-cayman
title: Mind & Body
description: Fitness | Yoga | Meditation
owner_url: https://github.com/LukeAndrewSmith
image_url: https://github.com/mind-and-body/mind-and-body.github.io/tree/master/img
owner_name: Luke Smith
